version: "3.7"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10.7
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
    networks:
      - vps-traefik
    ports:
      # The HTTP port
      - "8000:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  vps-traefik:
    name: vps-traefik
